# Generated by Django 4.2.3 on 2023-07-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('roast', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('D', 'Dark')], max_length=1, verbose_name='Roast')),
                ('countryOfOrigin', models.CharField(blank=True, max_length=100)),
                ('tastingNotes', models.CharField(blank=True, max_length=100)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Rating')),
                ('review', models.TextField(blank=True, max_length=250)),
                ('brewTips', models.TextField(blank=True, max_length=250)),
                ('image', models.URLField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Rating')),
                ('description', models.TextField(blank=True)),
                ('review', models.TextField(blank=True)),
                ('brewTips', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=300)),
            ],
        ),
    ]
