# Generated by Django 4.2.3 on 2023-07-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_coffee_image_maker_image_alter_coffee_brewtips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='maker',
            name='image',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
